language: java

jdk: oraclejdk8

install: true

script: ./gradlew build && CI=true ./gradlew check

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_deploy: tar -zcf variED-${TRAVIS_TAG}.tar.gz -C build .

deploy:
  - provider: releases
    file: variED-${TRAVIS_TAG}.tar.gz
    skip_cleanup: true
    on:
      repo: ekuiter/variED
      tags: true
      all_branches: true
    api_key:
      secure: l5Agcx9m6DJOMKr9o703gE9mIjcr+zI9iITUhaFoNw/fwpZRm1bvKgitlpfq83e7pzw8TAZdRPIL9WQRbvVRhpx/F4lEn5lF94tJJnrvhKjYolnw/UyZ9E8vgecYtYI15fEBeRwLyQQaSrtYD5XWCUEYVo5p0OJf+yTZoN+67ck1bsjeRICxSsvAl1GQySYvGj2teLe3euqpuFrv51VvCjubiCM0H7aperxJtJdXbJ1H9vCvylcnzn/SZp3hlOm455rooVPVZHHt7Ra4oF9SZn6nwXMpPdLpbnTWNNpbm0GTGxCgQ+KROeGRjx6O2JmnCC2V3Ql6ard+1luyuu9Dfwr6G/uFjBPLBEdSz2O24yogAh/sgzs8Rdt9HL/Wf0nSmLuRM83zKIROFWmdoic7VqRtwkd6sACBj9DxgtKob7IKYe7PWIgJzAiux8kQIbe2vZuNmzBcWbeCfa0NNhgpH4f45l5uHTIOESxYsLlAbFakyNMHkJ6sfDhA3GsUq/ztm4KcUxORyVfiRALNksErYCBE3jU+4dBAbQz5Vd+UbEZ53mE1p4SYOgvOJjmSd4Qm/HCvrYjb+Sw+F71w7uF5YQQnJT5I7VB3eEYVYoYO0B0724elbUB+DA/dNlNQpDiCdydfo1mTuQ7dqhDEZgMxWraLuf2mtxMFu/sNFf7DnS8=
  - provider: heroku
    app: varied
    skip_cleanup: true
    on:
      repo: ekuiter/variED
      tags: true
      all_branches: true
    api_key:
      secure: JSze8Ay+XXgoywWl0h1WoCBYhLRm+fC90jl39feorvVQIdFXUP8O5jF+kYD++8atlqvUnYVFVyfQCNqrCj0Fbzy4IUyroMB/vmf1rnrNsKeceVjbBmAGvg6KufAfw1gC1wbW2h8oEiG7QsMuAFNR7EX/z+Pi0udyoMlKZ7bcbUiV3aoT5uD9aMLivFFdzkv8VczbqkTnBjr3Ugz26INWC4q57ybULUamU7l4L8BixSAWVa9xh1VynSq805YzKE6/c9xNA3snRXjGTqOrTGfcQGCQ4myV0nPBGqNcscYYKeQeG1iYDXj9mMWH1WZLwnMufKs1Vawdk1A6YtK6ZWdsB4LDhqk1LJSjeJz1CS1ypBWVppFsTiNsQ6CIwuaGGNRTIH9BwJSX4N5hkoAosSNfemobNa1G/12mXRHCkCAar2wpj5DtllDoT4ODbS8l/seCUvKzrgwRlIUCvik//N91px6R+YWukPpB9bsFoPp3D8TRyu0Caoxh1su+vJvaeZtxnu/tCoEpYPd2sJsN7MWDYV25+ED70Z6B0RRj7EdDKibAofmzlkU684K66sElTN5R3kxHUEvQm+S1qZO9XnZLJGXCwb1RQU+PcB9+UeFN92WI7+4ItIYpljJgmtLxcbP8PnpyDJ9TEnUQ9DiuUwwsdNhTSMHHC6fV/H0/AE7+6T0=
  - provider: script
    script: bash -c 'git stash pop && ls | grep -v build | grep -v Procfile | grep -v app-build.json | xargs rm -rf && rm .travis.yml .gitignore && mv app-build.json app.json && git add -A && git add build -f'
    on:
      repo: ekuiter/variED
      all_branches: true
  - provider: pages
    target-branch: build
    skip-cleanup: true
    keep-history: true
    on:
      repo: ekuiter/variED
      all_branches: true
    github-token:
      secure: l5Agcx9m6DJOMKr9o703gE9mIjcr+zI9iITUhaFoNw/fwpZRm1bvKgitlpfq83e7pzw8TAZdRPIL9WQRbvVRhpx/F4lEn5lF94tJJnrvhKjYolnw/UyZ9E8vgecYtYI15fEBeRwLyQQaSrtYD5XWCUEYVo5p0OJf+yTZoN+67ck1bsjeRICxSsvAl1GQySYvGj2teLe3euqpuFrv51VvCjubiCM0H7aperxJtJdXbJ1H9vCvylcnzn/SZp3hlOm455rooVPVZHHt7Ra4oF9SZn6nwXMpPdLpbnTWNNpbm0GTGxCgQ+KROeGRjx6O2JmnCC2V3Ql6ard+1luyuu9Dfwr6G/uFjBPLBEdSz2O24yogAh/sgzs8Rdt9HL/Wf0nSmLuRM83zKIROFWmdoic7VqRtwkd6sACBj9DxgtKob7IKYe7PWIgJzAiux8kQIbe2vZuNmzBcWbeCfa0NNhgpH4f45l5uHTIOESxYsLlAbFakyNMHkJ6sfDhA3GsUq/ztm4KcUxORyVfiRALNksErYCBE3jU+4dBAbQz5Vd+UbEZ53mE1p4SYOgvOJjmSd4Qm/HCvrYjb+Sw+F71w7uF5YQQnJT5I7VB3eEYVYoYO0B0724elbUB+DA/dNlNQpDiCdydfo1mTuQ7dqhDEZgMxWraLuf2mtxMFu/sNFf7DnS8=